export const TRIANGLES_AMOUNT = 12;
export const RULES_SHOWING_TIME = 20000;
export const STARTING_TRIANGLE_SHOWING_TIME = 5000;
export const TIME_FOREACH_TRIANGLE = 5000;
export const SECOND_TRIANGLES_SHOWING_TIME = 60000;
